[package]
name = "rxing"
version = "0.1.0"
edition = "2021"
exclude = [
    "test_resources/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6"
fancy-regex = "0.10"
encoding = "0.2"
rand = "0.8.5"
urlencoding = "2.1.2"
uriparse = "0.6.4"
chrono = "0.4"
chrono-tz = "0.4"
image = {version = "0.24.3", optional = true}
imageproc = {version = "0.23.0", optional = true}

[features]
default = ["image"]
image = ["dep:image", "dep:imageproc"]